language: c
before_script: cd $TRAVIS_BUILD_DIR/
script:
- gcc main.c -o main
- "./main"
- tar czvf main.tar.gz ./main
deploy:
  provider: releases
  api_key:
    secure: 4HcQamEw3D847zh2HEQR+s/ZQL32ZnAKkPhpAZzKzrj8TMHUPZ3z1zBEbUdSLl7ssYJaNnmjdyK2ZO9xq4+X+tv7O2Wml5R73reGCxKfmoyWkA/yv7HvRO8I282HUQGyWUAfU2e315W6f8E2ClvcEF64/Cv3KxnPkw7Cdze5lkvk+otzSVJuA7S+SdhPAh/QcKYq+glqlC7GViNO1o9sCv0weMs5pDkhhH4h5pd1Nd7qqZ/CmxGjvVc5Hom7p9aNPKfTLyHoJ3ktfDgjwUSpDBfm7zt3OLhGQgExQ858+D5qnkrIgzU7wAJjLoVeKwZT9vIlrJ0RzJgF9cuu0v2a9jzRpzCGDR9bb7eRLK6CdtK+fZct8XpqPN4XWIEVowD88QPRgdgkbohVKAcSZ+srcvXCpGQd+e07ACK4NxL91eEaqSkU4pG74l6OnM46rRP1Ho9nb0JHGV3aPdSE6Qd56pUpp9MdkA47QaO6R54NUKaCXGLfjX6WQaZJumSUkSoyMP5uvn6W4B1lGPeNsZ6+PqHkpqw61nJoPpg45iiDUdhAVaxnD0cO2cTPpNo/5az6iCiUecWBtN72EkX16woy88CJ1xnNnbJqLWadrQ+oTqHv9yLJoQRMtLNG0exiFce/IQLgHVMWTTMVMRMZZ8SmWHaTxjWyGfVH9vOJTX4dRJo=
  file:
    - ./main.tar.gz
  skip_cleanup: true
  on:
    repo: roy4801/ci-test
    branch: master
    tags: true